name: Test and publish to PyPi

on:
  push:
    branches:
      - main
      - 'stable/**'
    tags:
      - 'v*'

jobs:
  tests:
    name: Regresion Tests
    uses: ./.github/workflows/tests.yml

  pypi-upload:
    runs-on: ubuntu-latest
    name: deploy
    needs: tests
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build --user
      - name: Build a source tarball
        run: >-
          python -m
          build
          --sdist
          --outdir dist/ .
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
